Header header

float64 pos_1
float64 mot_pos_1
float64 command_1
float64 delta_1
float64 pos_2
float64 mot_pos_2
float64 command_2
float64 delta_2
float64 pos_3
float64 mot_pos_3
float64 command_3
float64 delta_3
float64 pos_4
float64 mot_pos_4
float64 command_4
float64 delta_4

float64 height_1
float64 height_2
float64 height_3
float64 height_4

float64 current_height
float64 command_height

float64 roll
float64 pitch
bool    is_moving 

int32   motor_1_temp
int32   motor_2_temp
int32   motor_3_temp
int32   motor_4_temp

float64 load_1
float64 load_2
float64 load_3
float64 load_4

int32   mode
bool    pull_down_1 
bool    pull_down_2 
bool    pull_down_3 
bool    pull_down_4 
bool    out_of_range_1 
bool    out_of_range_2 
bool    out_of_range_3 
bool    out_of_range_4 
